### ISSUE TITLE
File transport doesn't work

### ISSUE THREAD

**Issue by lukebond** [tomrogers3/meteor-winston#4]
Steps to reproduce:
1. $ meteor create myapp; cd myapp
2. $ mrt add winston
3. Edit myapp.js, add the following line in the if(server) block:
   Winston.log('info', 'Hello logs');
4. Run meteor, observe the log output is correct.
5. Add the following two lines before the above-added winston line:
   Winston.add(Winston.transports.File, { filename: 'service.log' });
   Winston.remove(Winston.transports.Console);
6. Run meteor, observe that no log file is created.

Hopefully it's a mistake on my part, but I suspect this has something to do with Meteor's fibres approach vs the async approach of most Node modules?

**Comment by tomrogers3** [comment]
I believe this is a file path related issue rather than an issue with this library. This works for me if I use an absolute filepath for the log file. E.g. Winston.add(Winston.transports.File, { filename: '/tmp/service.log' });
You might need to check Meteor/Winston docs or StackOverflow answers etc. to check how to access the relative filepath you need. I hope this helps.

**Comment by lukebond** [comment]
Tom, you're absolutely right. Sorry for the time-waster and thanks for your prompt response!

**Comment by tomrogers3** [comment]
No probs. Best wishes for your project.
